apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    {{- include "labels" . | nindent 4 }}
    run: controller
spec:
  selector:
    matchLabels:
      run: controller
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
        run: controller
    spec:
      serviceAccountName: controller-access
      containers:
        - name: controller
          image: medinvention/k8s-sms-controller:{{ .Values.controller.release }}