apiVersion: v1
kind: ConfigMap
metadata:
  name: init-files
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  db: |
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS registration;
{{- end }}
    CREATE TABLE IF NOT EXISTS registration (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      host VARCHAR(255) NOT NULL,
      namespace VARCHAR(255) NOT NULL,
      pod VARCHAR(255) NOT NULL,
      ip VARCHAR(15) NOT NULL,
      active BOOLEAN DEFAULT TRUE,
      groupname VARCHAR(255) NOT NULL,
      service VARCHAR(255) NOT NULL,
      port INT(6) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP
    );
    CREATE INDEX selectidx ON registration(host, namespace);
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS access;
{{- end }}
    CREATE TABLE IF NOT EXISTS access (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      host VARCHAR(255) NOT NULL,
      ident VARCHAR(30) NOT NULL,
      message TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS error;
{{- end }}
    CREATE TABLE IF NOT EXISTS error (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      host VARCHAR(255) NOT NULL,
      ident VARCHAR(30) NOT NULL,
      message TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS link;
{{- end }}
    CREATE TABLE IF NOT EXISTS link (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      from_node_id INT(6) UNSIGNED NOT NULL,
      from_id INT(6) UNSIGNED NOT NULL,
      to_id INT(6) UNSIGNED NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX linkidx ON link(from_node_id, from_id, to_id);
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS request;
{{- end }}
    CREATE TABLE IF NOT EXISTS request (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      link INT(6) UNSIGNED NOT NULL,
      from_id INT(6) UNSIGNED NOT NULL,
      to_id INT(6) UNSIGNED NOT NULL,
      code VARCHAR(3) NOT NULL,
      at TIMESTAMP NOT NULL, 
      request_time FLOAT NOT NULL,
      response_time FLOAT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
{{- if not .Values.db.reuse }}
    DROP TABLE IF EXISTS node;
{{- end }}
    CREATE TABLE IF NOT EXISTS node (
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );