apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    {{- include "labels" . | nindent 4 }}
    run: db
spec:
  selector:
    matchLabels:
      run: db
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
        run: db
    spec:
      containers:
        - image: medinvention/mysql:arm
          name: mysql
          {{- with .Values.db.resources }}
          resources:
            {{-  toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MYSQL_DATABASE
              value: logs
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: rootpassword
          ports:
            - containerPort: 3306
          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', 'sleep 90 && mysql logs -uroot -p"$MYSQL_ROOT_PASSWORD" < /var/db.sql > /tmp/db.log 2>&1 &']
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /var/db.sql
              subPath: db
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
        - name: config-volume
          configMap:
            name: init-files
