apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  rootpassword: {{ .Values.db.password | b64enc }}
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}