apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  rootpassword: {{ .Values.db.password | b64enc }}
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}