apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-config
data:
  fluentd: |
    <source>
      @type syslog
      port 5140
      bind 0.0.0.0
      tag system
    </source>
    <match system.local7.*>
      @type sql
      host db-service.{{ .Release.Namespace }}.svc.cluster.local
      port 3306
      database logs
      adapter mysql2
      username mysql
      password mysql
      <table>
        column_mapping 'timestamp:created_at,host:host,ident:ident,message:message'
        table access
      </table>
      <table system.local6.*>
        column_mapping 'timestamp:created_at,host:host,ident:ident,message:message'
        table error
      </table>
    </match>