apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: syslog-udp
      port: 5140
      targetPort: 5140
      protocol: UDP
    - name: syslog-tcp
      port: 5140
      targetPort: 5140
      protocol: TCP
  selector:
    app: fluentd