apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: api-server-ingress
  labels:
    run: api
spec:
  rules:
    - host: {{ .Values.api.host | quote }}
      http:
        paths:
          - backend:
              serviceName: api-server-service
              servicePort: http
            path: /
  tls:
    - hosts:
      - {{ .Values.api.host | quote }}
      secretName: sms-tls