apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    run: api