apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-server
  labels:
    {{- include "labels" . | nindent 4 }}
    run: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      run: ui
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
        run: ui
    spec:
      containers:
        - name: ui-server
          image: medinvention/k8s-sms-ui:{{ .Values.ui.release }}
          ports:
            - containerPort: 80
          {{ if .Values.api.ingress.host }}
          env:
            - name: BACKEND_URL
              value: "http{{ if .Values.api.ingress.tls }}s{{ end }}://{{ .Values.api.ingress.host }}/"
          {{ end }}
    