apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ui-server
  labels:
    run: ui
spec:
  rules:
    - host: {{ .Values.ui.host | quote }}
      http:
        paths:
          - backend:
              serviceName: ui-server-service
              servicePort: http
            path: /
  tls:
    - hosts:
      - {{ .Values.ui.host | quote }}
      secretName: sms-tls