apiVersion: v1
kind: Service
metadata:
  name: ui-server-service
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    run: ui